// The comment box, dressed as part of the site.
//
// giscus renders inside an iframe, so styles.css cannot reach it. What it does
// accept is a URL to a stylesheet, which it loads in there — that is what this
// file builds. Inside the frame the markup is GitHub Primer, so the work is
// mostly rebinding Primer's variables to the paper-and-terracotta palette.
//
// Two stylesheets come out of one template, one per theme, because the frame
// has no idea which way the Tonon switch is pointing; theme.js tells it by
// swapping the URL. Keep the palettes below in step with the ones at the top
// of static/styles.css — same values, second home.

const FONTS =
  'https://fonts.googleapis.com/css2' +
  '?family=Alegreya:ital,wght@0,400..800;1,400..700' +
  '&family=Alegreya+Sans:ital,wght@0,400;0,500;0,700;1,400' +
  '&family=IBM+Plex+Mono:wght@400;500' +
  '&display=swap'

const light = {
  scheme: 'light',
  paper: '#f7f2e8',
  paperSunk: '#f0e9db',
  paperLift: '#fdfaf4',
  ink: '#1d1913',
  ink2: '#514738',
  ink3: '#877b66',
  rule: 'rgba(29, 25, 19, 0.15)',
  ruleSoft: 'rgba(29, 25, 19, 0.08)',
  accent: '#b4462a',
  accent2: '#8a6a2f',
  accentSoft: 'rgba(180, 70, 42, 0.11)',
  // Text that sits on top of a filled accent button.
  onAccent: '#fdfaf4',
  danger: '#a11f1f',
}

const dark = {
  scheme: 'dark',
  paper: '#14120e',
  paperSunk: '#1b1913',
  paperLift: '#201d16',
  ink: '#efe7d7',
  ink2: '#bcb09a',
  ink3: '#8b8069',
  rule: 'rgba(239, 231, 215, 0.16)',
  ruleSoft: 'rgba(239, 231, 215, 0.08)',
  accent: '#f2784c',
  accent2: '#d9a95a',
  accentSoft: 'rgba(242, 120, 76, 0.15)',
  onAccent: '#14120e',
  danger: '#f28b82',
}

export const themes = { light, dark }

/** The whole stylesheet for one palette. */
export function giscusTheme(c) {
  return `@import url("${FONTS}");

/* Generated by lib/giscus-theme.mjs — edit that, not this. */

main {
  color-scheme: ${c.scheme};

  /* -- surfaces and text ------------------------------------------------- */
  --color-canvas-default: ${c.paper};
  --color-canvas-overlay: ${c.paperLift};
  --color-canvas-inset: ${c.paperSunk};
  --color-canvas-subtle: ${c.paperSunk};
  --color-fg-default: ${c.ink};
  --color-fg-muted: ${c.ink2};
  --color-fg-subtle: ${c.ink3};
  --color-fg-on-emphasis: ${c.onAccent};
  --color-border-default: ${c.rule};
  --color-border-muted: ${c.ruleSoft};
  --color-neutral-muted: ${c.ruleSoft};
  --color-primer-shadow-inset: 0 0 transparent;

  /* -- links, mentions, focus rings -------------------------------------- */
  --color-accent-fg: ${c.accent};
  --color-accent-emphasis: ${c.accent};
  --color-accent-muted: ${c.accentSoft};
  --color-accent-subtle: ${c.accentSoft};

  /* -- buttons ----------------------------------------------------------- */
  --color-btn-text: ${c.ink};
  --color-btn-bg: ${c.paperLift};
  --color-btn-border: ${c.rule};
  --color-btn-shadow: 0 1px 0 ${c.ruleSoft};
  --color-btn-inset-shadow: 0 0 transparent;
  --color-btn-hover-bg: ${c.paperSunk};
  --color-btn-hover-border: ${c.accent};
  --color-btn-active-bg: ${c.paperSunk};
  --color-btn-active-border: ${c.accent};
  --color-btn-selected-bg: ${c.paperSunk};
  --color-btn-primary-text: ${c.onAccent};
  --color-btn-primary-bg: ${c.accent};
  --color-btn-primary-border: ${c.accent};
  --color-btn-primary-hover-bg: ${c.accent2};
  --color-btn-primary-hover-border: ${c.accent2};
  --color-btn-primary-selected-bg: ${c.accent2};
  --color-btn-primary-selected-shadow: 0 0 transparent;
  --color-btn-primary-disabled-text: ${c.ink3};
  --color-btn-primary-disabled-bg: ${c.paperSunk};
  --color-btn-primary-disabled-border: ${c.rule};
  --color-btn-primary-icon: ${c.onAccent};
  --color-btn-primary-counter-bg: ${c.accentSoft};

  /* -- the rest ---------------------------------------------------------- */
  --color-action-list-item-default-hover-bg: ${c.accentSoft};
  --color-segmented-control-bg: ${c.paperSunk};
  --color-segmented-control-button-bg: ${c.paper};
  --color-segmented-control-button-selected-border: ${c.accent};
  --color-social-reaction-bg-hover: ${c.paperSunk};
  --color-social-reaction-bg-reacted-hover: ${c.accentSoft};
  --color-danger-fg: ${c.danger};
  --color-success-fg: ${c.accent2};
  --color-attention-fg: ${c.accent2};
  --color-attention-muted: ${c.accentSoft};
  --color-attention-subtle: ${c.paperSunk};

  /* -- code, kept close to the site's own highlighting ------------------- */
  --color-prettylights-syntax-comment: ${c.ink3};
  --color-prettylights-syntax-constant: ${c.accent2};
  --color-prettylights-syntax-entity: ${c.accent};
  --color-prettylights-syntax-entity-tag: ${c.accent};
  --color-prettylights-syntax-keyword: ${c.accent};
  --color-prettylights-syntax-string: ${c.accent2};
  --color-prettylights-syntax-string-regexp: ${c.accent2};
  --color-prettylights-syntax-variable: ${c.ink2};
  --color-prettylights-syntax-storage-modifier-import: ${c.ink};
  --color-prettylights-syntax-markup-heading: ${c.ink};
  --color-prettylights-syntax-markup-bold: ${c.ink};
  --color-prettylights-syntax-markup-italic: ${c.ink};
  --color-prettylights-syntax-markup-list: ${c.accent2};
  --color-prettylights-syntax-markup-inserted-text: ${c.accent2};
  --color-prettylights-syntax-markup-deleted-text: ${c.danger};
  --color-prettylights-syntax-invalid-illegal-text: ${c.onAccent};
  --color-prettylights-syntax-invalid-illegal-bg: ${c.danger};
  --color-prettylights-syntax-sublimelinter-gutter-mark: ${c.ink3};
  --color-prettylights-syntax-brackethighlighter-angle: ${c.ink3};
  --color-prettylights-syntax-brackethighlighter-unmatched: ${c.danger};
  --color-prettylights-syntax-constant-other-reference-link: ${c.accent2};
}

/* --------------------------------------------------------------- type ---- */

main,
.gsc-comment-content,
.gsc-comment-author,
.gsc-comment-box-textarea,
.gsc-homepage-bg {
  font-family: "Alegreya", Palatino, Georgia, serif;
}

main { background: transparent; }

/* Metadata, buttons and tabs stay in the sans, as they do on the page. */
.gsc-comment-header,
.gsc-comment-box-tabs,
.gsc-comment-box-buttons,
.gsc-reactions,
.gsc-header,
.gsc-timeline-header,
.gsc-pagination,
.gsc-loading-text,
.btn {
  font-family: "Alegreya Sans", "Gill Sans", Optima, "Segoe UI", sans-serif;
}

code, pre, .gsc-comment-content code, .gsc-comment-content pre {
  font-family: "IBM Plex Mono", ui-monospace, "SF Mono", Menlo, monospace;
  font-size: 0.88em;
}

.gsc-comment-content { font-size: 1.05rem; line-height: 1.7; }
.gsc-comment-author-avatar { border-radius: 50%; }

/* Square the GitHub roundness off a little; the site has hard edges. */
.gsc-comment > div,
.gsc-comment-box,
.gsc-reactions-menu,
.btn {
  border-radius: 3px;
}

/* The rule above the box does the same job as .footer-rule on the page. */
.gsc-timeline { border-top: 1px solid ${c.ruleSoft}; padding-top: 1.4rem; }

.gsc-comment-content a { color: ${c.accent}; text-underline-offset: 2px; }
.gsc-comment-content blockquote {
  border-left: 2px solid ${c.accentSoft};
  color: ${c.ink2};
}

/* giscus's own "powered by" line, quieted down. */
.gsc-widget-a { color: ${c.ink3}; }
`
}
