import './style.css';
import {TouchControls,usesTouchControls} from './touch.js';
import {World,LABELS} from './world.js';
import {APPOINTMENTS,SIGN_TRAILS,traceSign,HOUSE_ORDER,validateHouse,shotSegment,validateCroquet,SIZE_MARKS,canResize,canPassLittleDoor} from './mechanics.js';
import {Sound} from './audio.js';
import {speakAnimal} from './animals.js';
import {reviewCheckpoint} from './review.js';
import {hotspotRoom,REGION_OFFSETS} from './overworld.js';
import {CHAPTERS,PUZZLES,ITEMS,initialState,restoreState,has,solve,collect,checkAnswer,objective,STORY_FRAGMENTS,ASSEMBLY_ORDER} from './puzzles.js';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORAGE='white-rabbit-save-v1';let state;try{state=restoreState(localStorage.getItem(STORAGE))}catch{state=initialState()}
if(usesTouchControls(state.settings.controls,{points:navigator.maxTouchPoints,coarse:matchMedia('(pointer: coarse)').matches})&&!state.started)state.settings.quality='low';
const review=import.meta.env.DEV?reviewCheckpoint():null;if(review)state=review.state;
const sound=new Sound();sound.enabled=state.settings.sound;let world;let touch;let modalOpen=false;let currentPuzzle=null;let hintLevels={};let toastTimer;let transition=false;let mode=null;let freshNotes=false;let signClick=null;
const persist=()=>{if(review)return;try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4400)}
function refresh(){const chapter=CHAPTERS.find(c=>c.room===state.room);$('#chapter-number').textContent=chapter.number;$('#chapter-title').textContent=chapter.title;$('#objective p').textContent=objective(state);$('#size-value').textContent=state.size;$('.size-meter i').style.width=`${state.size/55*100}%`;$('#item-count').textContent=state.inventory.length;$('#sound-toggle').style.opacity=state.settings.sound?'1':'.4';world?.sync(state);persist()}
function complete(id,note){if(!solve(state,id,note||PUZZLES[id]?.note))return;sound.success();const places={maze_garden:['roses','gardeners'],maze_court:['trial','tart','guard_original','guard_impostor'],maze_croquet:['croquet']};if(places[id]){state.discovered??=[];for(const place of places[id])if(!state.discovered.includes(place))state.discovered.push(place)}freshNotes=true;$('#note-dot').classList.add('unread');refresh()}
function addItem(id){collect(state,id);refresh();toast(`Added to your satchel: ${ITEMS[id].name}.`)}
function showModal(content,{wide=false,center=false,focus=null}={}){closeMode(false);touch?.reset();document.body.classList.add('dialog-open');modalOpen=true;world?.pause(true);$('#modal-content').innerHTML=content;$('#modal').classList.toggle('wide',wide);$('#modal').classList.toggle('center',center);$('#modal-backdrop').classList.remove('hidden','clue-view');$('#modal-backdrop').classList.toggle('world-clue',!!focus);$('#view-clue').classList.toggle('hidden',!focus);$('#view-clue').textContent='Look at the clue';$('#view-clue').setAttribute('aria-pressed','false');if(focus)world.examine(focus);$('#close-modal').focus({preventScroll:true});$('#modal').scrollTop=0;$('#modal-content').scrollTop=0}
function closeModal(){document.activeElement?.blur();document.body.classList.remove('dialog-open');sound.stopVoice();modalOpen=false;currentPuzzle=null;$('#modal-backdrop').classList.add('hidden');$('#modal-backdrop').classList.remove('clue-view');world?.endExamine();if(!state.started)world?.pause(false)}
function heading(eyebrow,title,description=''){return `<p class="eyebrow">${esc(eyebrow)}</p><h2 id="modal-title">${esc(title)}</h2>${description?`<p class="modal-description">${esc(description)}</p>`:''}`}
function info(title,text,eyebrow='A curious discovery',focus=null){showModal(heading(eyebrow,title,text),{focus})}
function hintMarkup(id){return `<div class="hint-row"><span>Your progress is saved automatically</span><button id="hint-button">A little nudge ↗</button></div><p id="hint-text" class="hint-text"></p>`}
function wireHints(id){$('#hint-button')?.addEventListener('click',()=>{const p=PUZZLES[id];const n=Math.min(hintLevels[id]||0,2);$('#hint-text').textContent=p.hints?.[n]||'Look closely at the objects around you.';hintLevels[id]=n+1;state.hints++;persist();sound.click()})}
function answerMarkup(placeholder='Enter your answer',max=12){return `<form class="answer-form" autocomplete="off"><input id="answer" aria-label="Answer" placeholder="${placeholder}" maxlength="${max}" spellcheck="false" autocapitalize="none" enterkeyhint="go"/><button type="submit">Try the lock ↗</button></form><p class="answer-feedback" role="status"></p>`}
function wireAnswer(id,after){const form=$('.answer-form');form?.addEventListener('submit',e=>{e.preventDefault();const input=$('#answer');if(checkAnswer(id,input.value)){complete(id);$('.answer-feedback').textContent='The mechanism yields.';$('.answer-feedback').classList.add('success');after?.();if(!after){closeModal();toast('A new discovery is waiting in your journal.')}}else{sound.fail();$('.answer-feedback').textContent=id==='shadow'&&input.value.trim()==='3'?'“I am only the shadow of myself.” There is another shape to include.':'Nothing moves. There is another way to read this.';input.select()}})}
function prerequisite(id){const req=PUZZLES[id]?.requires;if(req&&!has(state,req)){toast(objective(state));return false}return true}
function openPuzzle(id){
 const p=PUZZLES[id];if(!p)return;if(has(state,id)&&id!=='biscuit'&&id!=='bottle'){info(p.title,p.note,'A discovery you have made',id);return}if(!prerequisite(id))return;
 currentPuzzle=id;
 if(id==='caterpillar')speakAnimal(world,'caterpillar',9);
 if(id==='story'){storyPuzzle();return}if(id==='shadow'){shadowPuzzle();return}if(id==='biscuit'||id==='bottle'){heightPuzzle(id);return}if(id==='roses'){paintPuzzle();return}if(id==='trial'){trialPuzzle();return}if(id==='croquet'){croquetPuzzle();return}if(id==='effigies'){effigiesPuzzle();return}if(id==='assembly'){assemblyPuzzle();return}if(id==='signs'){signsPuzzle();return}if(id==='minutes'){minutesPuzzle();return}if(id==='messenger'){messengerPuzzle();return}if(id==='tea'){teaPuzzle();return}
 let extra='';
 if(id==='decree')extra=`<div class="alphabet">${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(l=>`<button data-letter="${l}" aria-label="Mark letter ${l}">${l}</button>`).join('')}</div><p class="hint-text">Tap letters to cross them off as you find them. Enter the three left over.</p>`;
 if(id==='final_lock'&&(!state.inventory.includes('amber')||!state.inventory.includes('ivory'))){toast('Read the house from both marked viewpoints first.');return}
 showModal(heading(p.eyebrow,p.title,p.description)+extra+answerMarkup(id==='arithmetic'?'The missing multiplier':id==='decree'?'Three missing letters':'Turn the lock…')+hintMarkup(id),{focus:id,wide:id==='signs'});currentPuzzle=id;
 if(id==='decree')$$('[data-letter]').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('present');sound.click()}));
 wireAnswer(id,()=>{
  if(id==='caterpillar'){closeModal();info('Advice from the caterpillar','“You are not quite yourself. Find the little violet mushroom that stands alone among the roots, west of my grove. And do keep your eyes open for things without a twin.”','A puff of smoke','caterpillar')}
  else if(id==='feet'){closeModal();toast('Your feet are back. A draft brushes your hair. Look up.');}
  else if(id==='decree'){closeModal();toast('The decree breaks its seal. The northern road behind the thrones is open.');}
  else if(id==='final_lock'){closeModal();finish()}
  else{closeModal();toast(id==='minutes'?'The cat’s colored crossing is awake.':id==='signs'?'The garden gate swings open.':'A new entry is waiting in your journal.');}
 });wireHints(id);
}
function storyPuzzle(){let dragged=-1;let order=[7,4,1,9,5,2,8,0,6,3];showModal(heading(PUZZLES.story.eyebrow,PUZZLES.story.title,PUZZLES.story.description)+`<p class="hint-text">Drag the memories into place, or use their arrow buttons.</p><div class="story-list"></div>`+answerMarkup('Four numbers in story order',4)+hintMarkup('story'),{wide:true,focus:'story'});currentPuzzle='story';
 const render=()=>{$('.story-list').innerHTML=order.map((n,i)=>`<div class="story-line" draggable="true" data-memory-position="${i}"><small>${String(i+1).padStart(2,'0')}</small><span>${esc(STORY_FRAGMENTS[n]).replace(/TWO|ONE|THREE|FIVE/g,s=>`<b>${s}</b>`)}</span><div><button data-up="${i}" aria-label="Move memory ${i+1} up" ${i===0?'disabled':''}>↑</button><button data-down="${i}" aria-label="Move memory ${i+1} down" ${i===9?'disabled':''}>↓</button></div></div>`).join('');$$('[data-memory-position]').forEach(row=>{row.ondragstart=e=>{dragged=+row.dataset.memoryPosition;e.dataTransfer.effectAllowed='move'};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();const target=+row.dataset.memoryPosition;if(dragged<0||dragged===target)return;const [memory]=order.splice(dragged,1);order.splice(target,0,memory);dragged=-1;sound.click();render()}});$$('[data-up]').forEach(b=>b.onclick=()=>move(+b.dataset.up,-1));$$('[data-down]').forEach(b=>b.onclick=()=>move(+b.dataset.down,1))};const move=(i,d)=>{if(i+d<0||i+d>9)return;[order[i],order[i+d]]=[order[i+d],order[i]];sound.click();render()};render();wireAnswer('story');wireHints('story');
}
function shadowPuzzle(){let turns=0;showMode('shadow','shadow',PUZZLES.shadow.title,PUZZLES.shadow.description,[['Turn left',()=>turn(-1)],['Turn right',()=>turn(1)],['Read the lock',()=>{closeMode();showModal(heading('The object and its shadow','More than a letter','Read both shapes as one number.')+answerMarkup('Two shapes, two digits',2)+hintMarkup('shadow'));wireAnswer('shadow');wireHints('shadow')}]],{position:[4.8,1.9,6.8],target:[4.8,1.75,4]});const turn=d=>{turns+=d;world.rotateLetter(turns);sound.click();$('#manipulation-description').textContent=Math.abs(turns)%2?'The brass M lies on its side. A second shape falls behind it.':'A brass M, waiting to be turned.'};}
function heightPuzzle(id){const p=PUZZLES[id],grow=id==='biscuit',verb=grow?'Grow':'Shrink';showModal(heading(p.eyebrow,p.title,p.description)+`<p class="height-current">Your current size: <strong>${state.size}</strong>. ${grow?'The cake only makes you taller.':'The bottle only makes you smaller.'}</p><div class="height-options">${SIZE_MARKS.map(n=>`<button data-height="${n}" aria-label="${verb} to ${n}" ${canResize(id,state.size,n)?'':'disabled'}>${n}</button>`).join('')}</div><p class="answer-feedback">${SIZE_MARKS.some(n=>canResize(id,state.size,n))?'Choose a mark '+(grow?'above':'below')+' your current size.':grow?'You are at the tallest mark. Use the bottle to shrink.':'You are at the smallest mark. Use the cake to grow.'}</p>`+hintMarkup(id),{focus:id});currentPuzzle=id;$$('[data-height]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.height);if(!canResize(id,state.size,n))return;state.size=n;refresh();closeModal();sound.tone(grow?330:165,1,.2);if(checkAnswer(id,n))complete(id);toast(`${grow?'You grow':'You shrink'} to ${n}. ${grow&&n===55?'The high table is within reach.':!grow&&canPassLittleDoor(n)?'The little doorway is now above your head.':''}`)});wireHints(id)}
function mushroomPuzzle(){showModal(heading(PUZZLES.mushroom.eyebrow,PUZZLES.mushroom.title,PUZZLES.mushroom.description)+`<button class="action-button" id="taste">Taste both sides of the mushroom</button>`,{focus:'mushroom'});world.examine('mushroom',{position:[-24,3,8.15],target:[-24,.95,8]});$('#taste').onclick=()=>{complete('mushroom');state.size=33;refresh();closeModal();toast('You are yourself again. The rabbit’s other appointments await.')}}
function kitchenPuzzle(){if(has(state,'kitchen'))return info(PUZZLES.kitchen.title,PUZZLES.kitchen.note,'The 5:40 appointment','kitchen');if(!state.inventory.includes('fan')){showModal(heading(PUZZLES.kitchen.eyebrow,PUZZLES.kitchen.title,PUZZLES.kitchen.description)+hintMarkup('kitchen'),{focus:'kitchen'});wireHints('kitchen');return}
 if(!world.canFanKitchen()){toast('Walk around to the open front of the kitchen.');world.navigate('kitchen',()=>kitchenPuzzle());return}
 let strokes=0;showMode('fan','kitchen','Too much pepper','Sweep your silk fan three times to clear the kitchen.',[['Sweep the fan',()=>{if(!world.canFanKitchen()){toast('Use the fan at the open front of the kitchen.');return}strokes++;world.swingTool();sound.tone(110+strokes*40,.25,.09,'triangle');if(world.smoke)world.smoke.children.forEach(o=>{o.position.x+=.5;o.scale.multiplyScalar(.8)});$('#manipulation-description').textContent=`The cloud thins. ${strokes} of 3 sweeps.`;if(strokes===3){complete('kitchen');closeMode();info('The cook’s evidence','“These are my tarts, every last one. Someone has been helping themselves.”\n\nShe gives you a scrap of the rabbit’s message. It reads “…where the minute hand points…”\n\nRemember the watch at this appointment.','The pepper clears')}}]],{position:[-6,2.5,-4.5],target:[-6,1.7,-8]});world.endExamine();world.focusMode='fan';world.equip('fan');$('#hud').classList.remove('hidden');$('#manipulation').classList.add('tool-mode')}
function paintPuzzle(){if(!state.inventory.includes('brush')){toast('Find the red paint and brush on the little table beside the hedge.');return}
 showMode('paint','roses','Paint the Queen’s roses','Walk around the flower bed. Aim at a white bloom and use your brush.',[['Paint nearest white rose',()=>paintWorldRose()],['Move closer to the bed',()=>world.navigate('roses',()=>toast('You are within reach of the rose bed.'))]],null);
 world.endExamine();world.focusMode='paint';world.equip('brush');$('#hud').classList.remove('hidden');$('#manipulation').classList.add('tool-mode');
}
function paintWorldRose(event){if(!world.paintNearestRose(event)){toast('Step close to the white roses and aim at a bloom.');return}sound.click();persist();const remaining=world.whiteRoseCount();$('#manipulation-description').textContent=remaining?`${remaining} white roses remain. Walk around the bed and find them.`:'Every rose is red.';if(!remaining){complete('roses');addItem('rose_token');closeMode();toast('The gardener slips a little wooden figure into your hand.')}}

function trialPuzzle(){
 if(!has(state,'kitchen')){toast('The cook’s evidence is missing. Revisit the pepper kitchen from your journal’s chapter menu.');return}
 if(!has(state,'tart_seen')||!has(state,'guards_seen')){showModal(heading('Before the hearing','Evidence before judgment','The Queen expects you to inspect the pepper tart and compare both guards. Their details matter.')+`<button id="inspect-evidence" class="action-button">Step back and investigate</button>`);$('#inspect-evidence').onclick=closeModal;return}
 const qs=[{q:'Who bakes the Queen’s tarts?',options:['The cook','The gardener','The Hatter'],answer:0},{q:'Who stole the tarts?',options:['The white rabbit','The Knave of Hearts','The King'],answer:1},{q:'How many differences expose the disguise?',options:['Five','Six','Seven','Eight'],answer:2},{q:'What was my second question?',options:['Who bakes the Queen’s tarts?','How many differences expose the disguise?','Who stole the tarts?'],answer:2}];let step=0;
 const render=()=>{const q=qs[step];showModal(heading('The Queen’s tribunal',q.q,'Choose your words carefully. The Queen dislikes repeating herself.')+`<div class="trial-progress">${qs.map((_,i)=>`<i class="${i<step?'done':''}"></i>`).join('')}</div><div class="trial-options">${q.options.map((o,i)=>`<button data-choice="${i}">${esc(o)}</button>`).join('')}</div><p class="answer-feedback"></p>`+hintMarkup('trial'),{focus:'trial'});$$('[data-choice]').forEach(b=>b.onclick=()=>{if(+b.dataset.choice===q.answer){sound.click();step++;if(step===4){complete('trial');addItem('guard_token');closeModal();toast('The disguise is exposed. The knave leaves you his wooden likeness.')}else render()}else{sound.fail();$('.answer-feedback').textContent='“Think before you speak,” says the Queen.'}});wireHints('trial')};render();
}
function inspectGuards(){let which=0;const show=()=>{world.examine(which?'guard_impostor':'guard_original',{position:[which?3.2:-3.2,1.5,-3.7],target:[which?3.2:-3.2,1.35,-6.2]});$('#manipulation-description').textContent=which?'The suspicious guard. Look closely at the same details on each uniform.':'The guard on duty. Remember the colors and details of his uniform.'};showMode('guards','guard_original','A borrowed uniform','Compare these two full-size guards. Small details may betray a disguise.',[['Guard on duty',()=>{which=0;show()}],['Suspicious guard',()=>{which=1;show()}],['I have compared them',()=>{complete('guards_seen','You inspected both uniforms. The Queen will expect your own count of the differences.');closeMode()}]],{position:[-3.2,1.5,-3.7],target:[-3.2,1.35,-6.2]})}
function croquetPuzzle(){
 let route=[],busy=false;world.resetCroquet();const setBusy=value=>{busy=value;for(const button of $$('#manipulation-actions button'))button.disabled=value&&button.textContent!=='Reset shot'};
 const render=()=>{showMode('croquet','croquet','A very unwilling croquet ball','Three rebounds, then the flag. Choose a cushion and watch the shot. The pale launch mark gives your first direction.',[['Cushion 4',()=>hit(4)],['Cushion 6',()=>hit(6)],['Cushion 7',()=>hit(7)],['Flag 1',()=>hit(1)],['Reset shot',()=>{route=[];setBusy(false);world.resetCroquet();$('#manipulation-description').textContent='Three rebounds, then the flag.'}]],{position:[8,10,-2],target:[8,0,-6]});};
 const hit=n=>{
  if(busy)return;if(n===1&&route.length!==3){toast('The Queen insists on three rebounds before the flag.');return}if(route.includes(n)){toast('That cushion is already behind you. Try a different line.');return}
  const from=route.at(-1)||'start';const result=shotSegment(from,n);setBusy(true);$('#manipulation-description').textContent='The hedgehog curls up and rolls…';
  world.rollCroquet(from,n,result.stop,()=>{setBusy(false);if(!result.ok){sound.fail();$('#manipulation-description').textContent=result.reason+' Try a different opening shot.';route=[];world.resetCroquet();return}
   route.push(n);sound.tone(260+route.length*85,.25,.14);$('#manipulation-description').textContent=n===1?'The flag! A perfect three-rebound shot.':`${route.length} rebound${route.length===1?'':'s'}. Where can the next straight shot go?`;
   if(n===1&&validateCroquet(route)){complete('croquet');addItem('alice_token');$('#manipulation-actions').innerHTML='<button id="croquet-done">Collect your prize</button>';$('#croquet-done').onclick=closeMode;}
  });
 };render();
}
function effigiesPuzzle(){
 if(!['rose_token','guard_token','alice_token'].every(i=>state.inventory.includes(i))){toast('Collect the gardener, knave and your own wooden effigy first.');return}
 let order=[];world.resetEffigies();
 const read=()=>{closeMode();showModal(heading('The joined figures','A useful command','Read the exposed marks from top to bottom.')+answerMarkup('Two digits',2)+hintMarkup('effigies'));wireAnswer('effigies');wireHints('effigies')};
 const put=n=>{if(order.includes(n))return;order.push(n);world.placeEffigy(n,order.length-1);sound.click();$('#manipulation-description').textContent=`From above: ${order.join(' → ')}`;if(order.length===3){$('#manipulation-actions').innerHTML='<button id="lower-heads">Lower the heads</button><button id="reset-figures">Rearrange the figures</button>';$('#reset-figures').onclick=effigiesPuzzle;$('#lower-heads').onclick=()=>{world.lowerEffigyHeads();$('#manipulation-description').textContent='The heads slide out of sight. Inspect the paint that remains.';$('#manipulation-actions').innerHTML='<button id="read-effigies">Read the joined number</button><button id="reset-figures">Rearrange the figures</button>';$('#read-effigies').onclick=read;$('#reset-figures').onclick=effigiesPuzzle;}}};
 showMode('effigies','effigies','Off with their heads','The paint is incomplete. Place an upper, middle and lower figure, then obey the command on the table.',[['You',()=>put('you')],['Knave',()=>put('knave')],['Gardener',()=>put('gardener')]],{position:[8,2.7,6.7],target:[8,2.4,1.5]});
}
function assemblyPuzzle(){
 if(has(state,'assembly')){info('The house is complete','Walk to the amber and ivory rings. Face the house. Its broken markings become two numbers from each side.');return}
 const placed=[...state.assembly];state.bridgeFaces??={};
 const description='Build from the ground up. The black king calls for 6, then 4. His face must point down, 8 against 8. Then red 6, 4, 2. The red king faces down, 9 against 9. Finish with red 5 and 7.';
 const update=()=>{state.assembly=[...placed];world.previewAssembly(placed,state.bridgeFaces);persist();$('#manipulation-description').textContent=`${placed.length} of 9 pieces. ${description}`;const controls=$('#manipulation-actions');controls.innerHTML='';
  const button=(label,fn,disabled=false)=>{const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;controls.append(b)};
  for(const label of ['♥ 7','♠ 4','♥ 2','Red bridge','♠ 6','♥ 5','Black bridge','♥ 4','♥ 6'])button(label,()=>{placed.push(label);sound.tone(220+placed.length*40,.35,.1);update()},placed.includes(label)||placed.length===9);
  for(const label of ['Black bridge','Red bridge'])if(placed.includes(label))button(`${label}: face ${state.bridgeFaces[label]?'down':'up'} ↻`,()=>{state.bridgeFaces[label]=!state.bridgeFaces[label];sound.click();update()});
  button('Remove last piece',()=>{placed.pop();update()},!placed.length);button('Test the structure',()=>{const result=validateHouse(placed,state.bridgeFaces);if(result.ok){complete('assembly');closeMode();toast('The house holds. Walk around it and inspect the two colored sides.')}else{sound.fail();toast(result.reason)}});
 };
 showMode('assembly','assembly','The kings’ impossible house',description,[],{position:[4.2,4.2,5.2],target:[0,2.6,-2]});update();
}
function showMode(name,id,title,description,actions,custom){closeModal();touch?.reset();document.body.classList.add('manipulating');mode=name;$('#manipulation').classList.toggle('comparison-mode',['guards','croquet','effigies','assembly','signs','tart','gardeners','door'].includes(name));$('#manipulation-label').textContent='EXAMINING THE WORLD';$('#manipulation-title').textContent=title;$('#manipulation-description').textContent=description;$('#manipulation-actions').innerHTML='';actions.forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;$('#manipulation-actions').append(b)});$('#manipulation').classList.remove('hidden');world.beginMode(name,id,custom);$('#hud').classList.add('hidden')}
function closeMode(resume=true){if(!mode)return;document.body.classList.remove('manipulating');if(mode==='croquet'&&world.ballPath)world.resetCroquet();signClick=null;world.equip(null);$('#manipulation').classList.remove('tool-mode');mode=null;$('#manipulation').classList.add('hidden');if(state.started)$('#hud').classList.remove('hidden');world.endExamine();if(!resume)world.pause(true)}
function clockSVG(h,m){const hand=(angle,length,width)=>`<line x1="50" y1="50" x2="${50+Math.sin(angle)*length}" y2="${50-Math.cos(angle)*length}" stroke="#293b30" stroke-width="${width}" stroke-linecap="round"/>`;return `<svg viewBox="0 0 100 100" role="img" aria-label="Clock showing ${h}:${String(m).padStart(2,'0')}"><circle cx="50" cy="50" r="47" fill="#cfba83"/><circle cx="50" cy="50" r="43" fill="#e8e0c5"/>${Array.from({length:12},(_,i)=>{const a=i/12*Math.PI*2;return `<text x="${50+Math.sin(a)*35}" y="${54-Math.cos(a)*35}" fill="#344331" font-size="9" text-anchor="middle">${i===0?'0':i}</text>`}).join('')}${hand((h+m/60)/12*Math.PI*2,21,3)}${hand(m/60*Math.PI*2,31,1.8)}<circle cx="50" cy="50" r="3" fill="#b3995d"/></svg>`}
async function interact(id){
 if(transition)return;sound.click();const region=hotspotRoom(id);if(world.overworld&&region!==state.room){state.room=region;world.room=region;refresh()}
 if(id==='rabbit')return info('Always, always late','“I cannot possibly wait. Begin with the book. Every good dream needs a beginning.”','The white rabbit','rabbit');
 if(id==='small_door'){
  return doorPuzzle();
 }
 if(id.startsWith('door_'))return toast('That lock has a different shape. Look for the triangular one.');
 if(id==='key'){if(state.size!==55)return toast('Your fingertips cannot reach. Compare the key’s height with the brass scale.');complete('biscuit');addItem('key');return}
 if(id==='ceiling'){if(has(state,'feet'))return changeRoom('garden');return toast('A distant opening in the ceiling. You cannot reach it yet.')}
 if(id==='schedule')return info('Four appointments','3:10 · Advice from a caterpillar\n4:25 · A letter from the messenger\n5:40 · A visit to the pepper kitchen\n6:00 · Tea, of course\n\n“All in good time,” says the rabbit. “Keep an eye on the long hands.”','An afternoon out of time','schedule');
 if(id==='mushroom'){if(!has(state,'caterpillar'))return toast('A solitary violet mushroom. Perhaps someone in the grove knows what it does.');if(has(state,'mushroom'))return info(PUZZLES.mushroom.title,PUZZLES.mushroom.note,'A discovery you have made','mushroom');return mushroomPuzzle();}
 if(id==='fan'){if(!has(state,'caterpillar'))return toast('The fan is tied down with a caterpillar’s silk. Keep the 3:10 appointment first.');addItem('fan');return}
 if(id==='kitchen')return kitchenPuzzle();
 if(id==='garden_exit'){if(!has(state,'signs'))return toast('The gate waits for the answer at the Cheshire crossing.');return toast('The Queen’s road is open. Follow the east path across the valley.')}
 if(id==='maze'){showModal(heading('You are 33','Three paths through the hedge','Each gate changes your number. Choose a path, then work out its new number.')+`<div class="pause-actions">${[['maze_garden','Garden · −4'],['maze_court','Tribunal · ×3'],['maze_croquet','Croquet · +16']].map(([n,l])=>`<button data-path="${n}">${l} ${has(state,n)?'✓':''}</button>`).join('')}</div>`);$$('[data-path]').forEach(b=>b.onclick=()=>openPuzzle(b.dataset.path));return}
 if(id==='brush'){if(!has(state,'maze_garden'))return toast('Open the garden path at the hedge dial first.');if(has(state,'gardeners_match'))addItem('brush');else gardenersPuzzle();return}
 if(id==='gardeners'){showMode('gardeners','gardeners','Three very worried gardeners','“We planted white. She ordered red. Our tools are on the little table. The seals know who owns them.”',[['Go to the tool chest',()=>{closeMode();world.navigate('brush',()=>interact('brush'))}]],{position:[-9,3.3,-3.5],target:[-9,1.1,-7.6]});return}
 if(id==='tart'){if(!has(state,'maze_court'))return toast('Open the tribunal path at the hedge dial first.');return tartPuzzle()}
 if(id==='guard_original'||id==='guard_impostor'){if(!has(state,'maze_court'))return toast('Open the tribunal path at the hedge dial first.');return inspectGuards()}
 if(id==='court_exit'){if(!has(state,'decree'))return toast('The Queen’s decree seals this door. Find the three missing letters.');return toast('The northern road is open. Walk through the gap behind the thrones and follow it to the tower.')}
 if(id==='structure')return has(state,'assembly')?info('A house made of angles','Walk to the two colored rings on the floor. Face the structure from each side. Its painted fragments should align.'):assemblyPuzzle();
 if(id==='amber_view'||id==='ivory_view'){if(!has(state,'assembly'))return toast('Assemble the house before reading its sides.');const side=id.split('_')[0];world.viewRing(side);viewFound(side);showMode('view',id,side==='amber'?'The amber side':'The ivory side','From this exact spot, the scattered strokes become whole.',[],{position:[side==='amber'?-6:6,1.7,-2],target:[0,2.7,-2]});return}
 if(id==='forest_map')return worldMap();
 if(id==='bridge_note')return info('Three crossings','The stream divides the woods. Three timber bridges cross it. The old kitchen stands beyond the western bridge; the tea clearing lies beyond the eastern one.','A river inscription','bridge_note');
 if(id==='fan_note')return info('A misplaced fan','“I left my blue fan among the broken pillars. Perhaps the caterpillar remembers where.”','A note snagged on a branch','fan_note');
 if(id==='cat_eyes')return info('Follow my eyes','The cat’s left eye shines amber. His right is pale ivory.\n\nHe smiles toward the two rings on the floor.','One last piece of advice','cat_eyes');
 openPuzzle(id);
}
function doorPuzzle(){
 const unlocked=has(state,'door_unlock'),fits=canPassLittleDoor(state.size),key=state.inventory.includes('key');
 const description=!unlocked?'A three-sided keyway in the brass plate. Compare its shape with the key.':fits?'The open frame is taller than you. You can walk through the passage.':'The door is open, but the frame is below your head. The bottle can make you smaller.';
 const actions=[];
 if(!unlocked&&key)actions.push(['Turn the triangular key',()=>{complete('door_unlock','The matching key opened door 6. The passage is much smaller than the hall.');closeMode();toast('The key turns and the door swings open. Compare the opening with your height.')}]);
 else if(unlocked&&fits)actions.push(['Walk through door 6',()=>{closeMode();world.navigate('small_door',()=>world.enterLittleDoor())}]);
 else if(!key)actions.push(['Look for the matching key',()=>{closeMode();toast('The little key rests on the high table.')}]);
 showMode('door','small_door','Door 6 · the triangular lock',description,actions,{position:[-2.4,.58,-9.6],target:[-2.4,.41,-11.48]});
}
function viewFound(side){if(!state.inventory.includes(side)){addItem(side);complete('view_'+side,ITEMS[side].description);toast(side==='amber'?'From the amber ring, the strokes align into 78.':'From the ivory ring, the strokes align into 32.')}}
async function changeRoom(room){
 if(transition)return;transition=true;closeModal();closeMode();world.pause(true);const ch=CHAPTERS.find(c=>c.room===room);const el=$('#chapter-transition');el.querySelector('.eyebrow').textContent=`CHAPTER ${ch.number}`;el.querySelector('h2').textContent=ch.title;el.querySelector('.chapter-subtitle').textContent=ch.subtitle;el.classList.remove('hidden');sound.chapter();
 try{if(room==='garden'){complete('ceiling','You looked up and found the way out. The rabbit is waiting in the garden.');if(!has(state,'mushroom'))state.size=11}state.room=room;await world.load(room,state);world.active=true;world.title=false;refresh();await new Promise(r=>setTimeout(r,1200));world.pause(false)}catch(e){toast('This place could not load. Try opening the game again.');console.error(e)}finally{el.classList.add('hidden');transition=false}
}
function journal(){freshNotes=false;$('#note-dot').classList.remove('unread');showModal(heading('A record of impossible things','Your journal','Clues you have uncovered stay here. You can revisit any chapter you have reached.')+`<div class="route-actions">${CHAPTERS.filter((c,i)=>i===0||i===1&&has(state,'ceiling')||i===2&&has(state,'signs')||i===3&&has(state,'decree')).map(c=>`<button data-room="${c.room}">${c.number} · ${c.room}</button>`).join('')}</div><div class="journal-list">${state.notes.length?state.notes.toReversed().map(n=>`<article class="journal-entry"><small>${esc(n.room)}</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></article>`).join(''):'<p class="empty-message">The pages are empty. Begin with the open storybook.</p>'}</div>`);$$('[data-room]').forEach(b=>b.onclick=()=>changeRoom(b.dataset.room))}
function satchel(){const icons={key:'⚿',fan:'◒',brush:'╱',pawn:'♟',eye:'◉'};showModal(heading('Small things with peculiar uses','Your satchel','Items are used when you examine a matching object in the world.')+state.inventory.map(id=>`<div class="inventory-item"><span class="item-icon">${icons[ITEMS[id]?.icon]||'◇'}</span><div><h3>${esc(ITEMS[id]?.name||id)}</h3><p>${esc(ITEMS[id]?.description||'')}</p></div></div>`).join('')+(state.inventory.length?'':'<p class="empty-message">Nothing in your pockets yet.</p>'))}
function nearby(){const close=world.nearby();const nearIds=new Set(close.map(o=>o.id));const far=Object.entries(world.hotspots).filter(([id,o])=>o.visible&&LABELS[id]&&!nearIds.has(id)&&!id.startsWith('door_')&&id!=='structure'&&id!=='ceiling'&&(!world.overworld||hotspotRoom(id)===state.room)&&(!world.overworld||state.discovered?.includes(id)||['schedule','caterpillar','messenger','kitchen','tea','maze','assembly','final_lock','cat_eyes','garden_exit','court_exit','forest_map'].includes(id))).map(([id])=>({id,label:LABELS[id]}));showModal(heading('Follow your curiosity','Explore your surroundings','Inspect objects within reach, or walk to a landmark. You can also explore freely with the movement controls.')+`<div class="nearby-list">${close.map(o=>`<button class="nearby-item" data-object="${o.id}"><span>${esc(o.label)}</span><small>Examine ↗</small></button>`).join('')}</div><p class="eyebrow" style="margin-top:24px">FARTHER AWAY</p><div class="nearby-list">${far.map(o=>`<button class="nearby-item" data-walk="${o.id}"><span>${esc(o.label)}</span><small>Walk over ↗</small></button>`).join('')}</div>`);$$('[data-object]').forEach(b=>b.onclick=()=>{const id=b.dataset.object;closeModal();interact(id)});$$('[data-walk]').forEach(b=>b.onclick=()=>{const id=b.dataset.walk;closeModal();world.navigate(id,()=>interact(id))})}

function worldMap(){showModal(heading('A valley with many wrong turns','The lost woods','Explore the clearings in any order. The river has three bridges. The Queen’s road runs east, and the tower stands north of her court.')+`<svg class="map-svg" viewBox="0 0 680 430" role="img" aria-label="Map of the connected Wonderland valley"><rect width="680" height="430" fill="#15342b"/><path d="M80 45 Q70 120 100 170 T100 370 L365 370 L365 235 L520 235 L520 110 L600 110 L600 30 L510 30 L510 160 L365 160 L365 50Z" fill="#3b5638" stroke="#a6a775" stroke-width="2"/><path d="M75 205 Q230 190 365 210" stroke="#548c87" stroke-width="14" fill="none"/><path d="M230 330 V85 M145 265 L145 145 M315 265 V155 M230 100 L530 195 L552 65" stroke="#b9a777" stroke-width="3" stroke-dasharray="5 6" fill="none"/>${[['The arrival',230,350],['The ruins',128,290],['The caterpillar',143,241],['The messenger',309,294],['Pepper cottage',144,119],['Tea clearing',316,128],['Cheshire crossing',230,77],['The Queen’s grounds',545,210],['The impossible house',550,60]].map(([l,x,y])=>`<circle cx="${x}" cy="${y}" r="4" fill="#e2c381"/><text x="${x}" y="${y-12}" fill="#d9d4b7" font-size="10" text-anchor="middle">${l}</text>`).join('')}</svg><p class="hint-text">Explore with the movement controls. The nearby-objects menu only lists small items after you have approached their hiding places.</p>`,{wide:true})}
function settings(){showModal(heading('Make yourself comfortable','Settings')+`<label class="settings-row">Ambient sound<input id="setting-sound" type="checkbox" ${state.settings.sound?'checked':''}/></label><label class="settings-row">Look sensitivity<input id="setting-sensitivity" type="range" min="0.4" max="2" step="0.1" value="${state.settings.sensitivity}"/></label><label class="settings-row">Controls<select id="setting-controls"><option value="auto">Automatic detection</option><option value="touch">Touch · two thumbs</option><option value="desktop">Keyboard & mouse</option></select></label><label class="settings-row">Graphics<select id="setting-quality"><option value="high">High · soft light & bloom</option><option value="medium">Medium · reduced resolution</option><option value="low">Low · no shadows</option></select></label><p class="modal-description">Your progress is saved in this browser. Sound begins after you start the game.</p>`,{center:!state.started});$('#setting-controls').value=state.settings.controls||'auto';$('#setting-controls').onchange=e=>{state.settings.controls=e.target.value;touch.update();refresh()};$('#setting-quality').value=state.settings.quality;$('#setting-sound').onchange=e=>{state.settings.sound=e.target.checked;sound.start();sound.set(state.settings.sound);refresh()};$('#setting-sensitivity').oninput=e=>{state.settings.sensitivity=+e.target.value;refresh()};$('#setting-quality').onchange=e=>{state.settings.quality=e.target.value;world.setQuality(e.target.value);refresh()}}
function howTo(){showModal(heading('Follow your curiosity','How to play','Explore each space. Inspect anything that seems out of place. The world rewards a second look.')+`<div class="controls-grid"><span>W A S D</span><span>Walk. Hold Shift to move faster.</span><span>Mouse drag</span><span>Look around. Or capture your mouse for free look.</span><span>Arrow keys</span><span>Move forward / back and turn left / right.</span><span>E / Click</span><span>Inspect the object you are looking at.</span><span>J / I</span><span>Open your journal or satchel.</span><span>Tab</span><span>Choose from objects within reach.</span><span>Esc</span><span>Step back or pause.</span></div><p class="modal-description">There is no countdown and no penalty for a wrong answer. Locks offer three levels of hints. On phones, turn the screen sideways. Drag the left joystick to walk. Drag the right LOOK pad to turn, then tap Interact. Explore lets you choose a nearby object. Both thumbs work together. Full screen is optional.</p><p class="source-note">An independent 3D adaptation of the puzzle progression in <a href="https://www.nos-jeux-de-societe.fr/wp-content/uploads/2023/08/Solution-Unlock-heroic-adventure-a-la-poursuite-du-lapin-blanc.pdf" target="_blank" rel="noreferrer">Unlock! Heroic Adventures: In Pursuit of the White Rabbit</a>. Original environments, models, interface and English text. Not affiliated with Space Cowboys.</p>`,{center:true})}
function pause(){showModal(heading('The rabbit can wait','A moment out of time')+`<div class="pause-actions"><button id="resume">Return to the dream ↗</button><button id="pause-settings">Settings</button><button id="pause-controls">How to play</button><button id="return-title">Return to title</button><a class="back-to-post" href="/after-the-white-rabbit/">Read the making-of ↗</a></div>`,{center:true});$('#resume').onclick=closeModal;$('#pause-settings').onclick=settings;$('#pause-controls').onclick=howTo;$('#return-title').onclick=()=>{closeModal();world.title=true;world.active=false;touch?.reset();touch?.update();$('#hud').classList.add('hidden');$('#title-screen').classList.remove('hidden');$('#begin').innerHTML='Continue your dream <span>↗</span>';$('#new-game').classList.remove('hidden')}}
function finish(){state.completed=true;refresh();sound.chapter();showModal(heading('And then, morning','You found your way home.','The house slips out of focus. The rabbit’s watch falls quiet. Somewhere on the riverbank, someone is calling your name.')+`<div class="completion-stat"><div><strong>${Math.floor(state.minutes)}</strong><span>MINUTES IN WONDERLAND</span></div><div><strong>${Object.keys(PUZZLES).filter(id=>has(state,id)).length}</strong><span>PUZZLES SOLVED</span></div><div><strong>${state.hints}</strong><span>HINTS USED</span></div></div><button class="primary-button" id="end-journal">Read your story <span>↗</span></button><button class="text-button" id="dream-again">Dream again</button>`,{center:true});$('#end-journal').onclick=journal;$('#dream-again').onclick=confirmNew}
function confirmNew(){showModal(heading('A new beginning','Begin a new dream?','Your current journal and progress will be replaced.')+`<button id="confirm-new" class="action-button">Begin again</button><button id="keep-dream" class="text-button" style="margin-left:20px">Keep this dream</button>`,{center:true});$('#keep-dream').onclick=closeModal;$('#confirm-new').onclick=async()=>{state=initialState();persist();closeModal();await start(true)}}
async function start(fresh=false){touch?.reset();if(fresh&&touch?.enabled)state.settings.quality='low';if(touch?.enabled&&window.top===window.self)touch.fullscreen();sound.start();sound.set(state.settings.sound);$('#title-screen').classList.add('hidden');$('#hud').classList.remove('hidden');state.started=true;if(fresh||world.room!==state.room)await world.load(state.room,state);world.start();touch?.update();if(review?.at&&world.boxes[review.at]){const box=world.boxes[review.at];world.camera.position.set((box.min.x+box.max.x)/2,1.7,box.max.z+2.2);world.yaw=0;world.pitch=0}world.setQuality(state.settings.quality);refresh();if(fresh||!state.notes.length)toast('Start with the open book on the table to your left. Drag to look around.');if(state.completed)finish()}
$('#view-clue').onclick=()=>{document.activeElement?.blur();const viewing=$('#modal-backdrop').classList.toggle('clue-view');$('#view-clue').textContent=viewing?'Back to the puzzle':'Look at the clue';$('#view-clue').setAttribute('aria-pressed',String(viewing));world.updateComposition()};
// Mobile keyboards resize the visible viewport without consistently changing
// innerHeight. Keep the whole dialog, including Close and Submit, above it.
function updateDialogViewport(){const v=window.visualViewport;document.documentElement.style.setProperty('--dialog-height',`${v?.height||innerHeight}px`);document.documentElement.style.setProperty('--dialog-top',`${v?.offsetTop||0}px`);}
window.visualViewport?.addEventListener('resize',updateDialogViewport);window.visualViewport?.addEventListener('scroll',updateDialogViewport);window.addEventListener('resize',updateDialogViewport);updateDialogViewport();
$('#close-modal').onclick=closeModal;$('#leave-manipulation').onclick=()=>closeMode();$('#begin').onclick=()=>start();$('#new-game').onclick=confirmNew;$('#title-settings').onclick=settings;$('#how-to-play').onclick=howTo;$('#journal-toggle').onclick=journal;$('#satchel-toggle').onclick=satchel;$('#nearby-toggle').onclick=nearby;$('#pause-toggle').onclick=pause;$('#mouse-lock').onclick=()=>world.lock();$('#sound-toggle').onclick=()=>{state.settings.sound=!state.settings.sound;sound.start();sound.set(state.settings.sound);refresh()};
document.addEventListener('keydown',e=>{
 if(e.code==='Escape'){e.preventDefault();if(mode)closeMode();else if(modalOpen)closeModal();else if(state.started&&!world.title)pause();return}
 if(modalOpen&&e.code==='Tab'){const focusables=$$('#modal button:not(:disabled),#modal input,#modal select,#modal a');if(focusables.length){const current=focusables.indexOf(document.activeElement);const next=e.shiftKey?(current<=0?focusables.length-1:current-1):(current+1)%focusables.length;focusables[next].focus();e.preventDefault()}return}
 if(e.target.matches('input,select,textarea')||!state.started||world.title)return;if(mode){if(e.code==='KeyE'&&mode==='paint')paintWorldRose();return}
 if(e.code==='KeyM'){e.preventDefault();worldMap()}else if(e.code==='KeyJ'){e.preventDefault();modalOpen?closeModal():journal()}else if(e.code==='KeyI'){e.preventDefault();modalOpen?closeModal():satchel()}else if(e.code==='KeyE'&&!modalOpen){e.preventDefault();world.interact()}else if(e.code==='Tab'&&!modalOpen){e.preventDefault();nearby()}
});
setInterval(()=>{if(state.started&&!world?.title&&!world?.suspended&&!modalOpen&&!document.hidden&&!state.completed){state.minutes+=1/60;persist()}},1000);
async function boot(){try{
 world=new World($('#world'),{onInteract:interact,onMessage:toast,onStep:()=>sound.step(),onTarget:hit=>{const el=$('#interaction');el.classList.toggle('hidden',!hit);$('#crosshair').classList.toggle('active',!!hit);$('#touch-action').classList.toggle('ready',!!hit);if(hit)el.querySelector('span').textContent=LABELS[hit.id]||'Examine'},onRegion:region=>{state.room=region;refresh();toast(CHAPTERS.find(c=>c.room===region).title)},onDiscover:id=>{state.discovered??=[];if(!state.discovered.includes(id)){state.discovered.push(id);persist()}},onModeClick:(name,e)=>{if(name==='paint')paintWorldRose(e);else if(name==='fan')$('#manipulation-actions button')?.click();else if(name==='signs'){const hit=world.signAt(e);if(hit)signClick?.(hit.trail,hit.index)}},onDoorPass:()=>{if(transition||modalOpen||mode||has(state,'feet'))return;complete('bottle');complete('door_passed','You walked through the little doorway. A strange measuring dial waits inside.');openPuzzle('feet')},onLookUp:()=>{if(!transition)changeRoom('garden')},onView:viewFound,onLock:locked=>{$('#mouse-lock').textContent=locked?'Mouse captured · Esc to release':'Capture mouse ↗'}});
 touch=new TouchControls({getWorld:()=>world,getState:()=>state,onAction:()=>{if(mode==='paint')paintWorldRose();else if(mode==='fan')$('#manipulation-actions button')?.click();else if(world.highlight)world.interact();else toast('Aim at an object, or tap Explore to choose one nearby.')},onExplore:nearby,onMessage:toast});
 await world.load('hall',state);world.setQuality(state.settings.quality);$('#loading').classList.add('hidden');$('#title-screen').classList.remove('hidden');if(state.started){$('#begin').innerHTML='Continue your dream <span>↗</span>';$('#new-game').classList.remove('hidden')}
 // A stable readiness signal is useful to browser smoke tests without exposing game state.
 document.body.dataset.ready='true';if(import.meta.env.DEV&&review){const badge=document.createElement('div');badge.textContent='Developer checkpoint · saves disabled';Object.assign(badge.style,{position:'fixed',bottom:'3px',left:'8px',fontSize:'8px',color:'#d8bd81',zIndex:'20',pointerEvents:'none'});document.body.append(badge)}
}catch(error){console.error(error);$('#loading').innerHTML=`<div class="fatal"><h2>The dream could not load.</h2><p>${esc(error.message)}</p><p>This game needs a browser with WebGL 2 enabled.</p><button class="action-button" onclick="location.reload()">Try again</button></div>`}}
boot();

function messengerPuzzle(){
 const dialogue='I won the right to carry this invitation. You won? Won, of course. Won, won, won!';
 showModal(heading('The 4:25 appointment','The messenger’s strange reply','The messenger keeps repeating himself. Listen carefully. The invitation has room for just one seal.')+`<button id="listen-messenger" class="action-button">Listen to the messenger</button><details class="spoken-transcript"><summary>Read the conversation</summary><p>${esc(dialogue)}</p></details>`+answerMarkup('The invitation’s seal',4)+hintMarkup('messenger'),{focus:'messenger'});
 $('#listen-messenger').onclick=()=>{speakAnimal(world,'messenger',12);if(!sound.speak(dialogue,.93,1.15)){document.querySelector('.spoken-transcript').open=true;toast('Read the conversation below. Say the repeated word aloud.')}};wireAnswer('messenger');wireHints('messenger');
}
function teaPuzzle(){
 showModal(heading('The 6:00 appointment','An invitation to tea',PUZZLES.tea.description)+`<div class="tea-invitation"><button id="hat-tag" title="Inspect the Hatter’s price tag">10/6</button><span>A cup waits beside a one-letter seal.</span></div><p id="hatter-reply" class="hint-text"></p>`+answerMarkup('One letter',1)+hintMarkup('tea'),{focus:'tea'});
 const replies=['“That is the price of the hat. You cannot possibly drink a price.”','“Six shillings, ten pence? Ten shillings, six pence? I have never asked the hat.”','“More tea? You have had none, so it is quite easy to have more.”'];let i=0;$('#hat-tag').onclick=()=>{$('#hatter-reply').textContent=replies[i++%replies.length];sound.click()};wireAnswer('tea');wireHints('tea');
}
function minutesPuzzle(){
 if(!APPOINTMENTS.every(a=>has(state,a.id))){toast('Keep all four appointments and collect their messages.');return}
 const order=[2,0,3,1];showModal(heading('The rabbit’s lost minutes','Four meetings, one sentence',PUZZLES.minutes.description)+'<div id="appointment-pieces"></div>'+answerMarkup('Four watch wheels',4)+hintMarkup('minutes'),{wide:true,focus:'minutes'});
 const render=()=>{$('#appointment-pieces').innerHTML=order.map((n,i)=>{const a=APPOINTMENTS[n];return `<article class="appointment-piece"><div class="clock-ui">${clockSVG(a.h,a.m)}</div><div><small>${esc(a.title)}</small><p>${esc(a.clue)}</p></div><div><button data-scrap-up="${i}" aria-label="Move message ${i+1} earlier" ${i===0?'disabled':''}>↑</button><button data-scrap-down="${i}" aria-label="Move message ${i+1} later" ${i===3?'disabled':''}>↓</button></div></article>`}).join('');
  for(const [key,d] of [['scrapUp',-1],['scrapDown',1]])$$(`[data-${key==='scrapUp'?'scrap-up':'scrap-down'}]`).forEach(b=>b.onclick=()=>{const i=+b.dataset[key];[order[i],order[i+d]]=[order[i+d],order[i]];sound.click();render()});
 };render();wireAnswer('minutes');wireHints('minutes');
}
function signsPuzzle(){
 if(!has(state,'minutes')){toast('The crossing waits for the rabbit’s watch to open.');return}
 let selected='green';const progress={};world.clearSignLines();
 const location=(trail,index)=>{if(index===0)return 'Start sign';const [x,z]=trail.points[index];return `${z<-.5?'Upper':z>.5?'Lower':'Middle'} ${x<-.5?'left':x>.5?'right':'center'} sign`};
 const render=()=>{const controls=$('#manipulation-actions');controls.innerHTML='';const add=(label,fn,active=false)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;b.classList.toggle('selected',active);controls.append(b)};
  for(const trail of SIGN_TRAILS)add(trail.name,()=>{selected=trail.id;world.selectSignColor(selected);render()},selected===trail.id);
  const trail=SIGN_TRAILS.find(t=>t.id===selected),closed=trail.points[0].join()===trail.points.at(-1).join(),count=trail.points.length-(closed?1:0);
  for(const index of [3,1,4,0,5,2].filter(i=>i<count))add(location(trail,index),()=>signClick(selected,index));
  add('Clear the traced lines',()=>{for(const k of Object.keys(progress))delete progress[k];world.clearSignLines();$('#manipulation-description').textContent='Start at a ring. Follow the directions of the arrows of that color.'});
  add('Read the crossing lock',()=>{closeMode();showModal(heading('The Cheshire crossing','Which way is out?','Read what the trails draw. The colored E X I T letters above the table give their order.')+answerMarkup('Four digits',4)+hintMarkup('signs'));wireAnswer('signs');wireHints('signs')});
 };
 showMode('signs','signs','The Cheshire crossing','Start at a ring. Follow the directions of the arrows of that color. Click the signs, or choose their positions below.',[],{position:[0,5.5,-9.6],target:[0,1.2,-11]});
 signClick=(trail,index)=>{if(trail!==selected){toast('Keep following the same color.');return}if(traceSign(progress,trail,index)){world.traceSignLine(trail,progress[trail]);sound.click();const data=SIGN_TRAILS.find(t=>t.id===trail);$('#manipulation-description').textContent=progress[trail].length===data.points.length?'A shape emerges from the trail. Remember it, then follow another color.':'The line follows your finger. Where does the next arrow point?'}else toast('That sign is not where the last arrow points. Look along its direction.')};world.selectSignColor(selected);render();
}
function gardenersPuzzle(){
 const chosen=new Set();showModal(heading('The gardeners’ tool chest','Who left these tools?','Three spade seals hold the latch. Choose the numbers worn by the three gardeners.')+`<div class="seal-grid">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-seal="${n}" aria-label="Spade seal ${n}">♠ ${n}</button>`).join('')}</div><button id="open-tools" class="action-button">Open the tool chest</button><button id="find-gardeners" class="text-button">Look at the gardeners</button><p class="answer-feedback"></p>`+hintMarkup('gardeners_match'),{focus:'brush'});
 $$('[data-seal]').forEach(b=>b.onclick=()=>{const n=+b.dataset.seal;if(chosen.has(n))chosen.delete(n);else if(chosen.size<3)chosen.add(n);b.classList.toggle('selected',chosen.has(n));sound.click()});
 $('#open-tools').onclick=()=>{if(checkAnswer('gardeners_match',[...chosen].sort().join(''))){complete('gardeners_match');addItem('brush');closeModal();toast('The spade seals turn. The red paint and brush are yours.')}else{sound.fail();$('.answer-feedback').textContent='The three seals do not match the gardeners’ tunics.'}};
 $('#find-gardeners').onclick=()=>{closeModal();world.navigate('gardeners',()=>interact('gardeners'))};wireHints('gardeners_match');
}
function tartPuzzle(){
 const choose=suit=>{if(suit==='hearts'){complete('tart_seen','The tart and its crumbs trace a heart. The culprit’s suit is hearts.');closeMode();toast('A heart. Keep that evidence for the Queen.')}else{sound.fail();toast('Look at the outline made by the crumbs and the stolen slice.')}};
 showMode('tart','tart','A trail of crumbs','A stolen slice. Crumbs that lead somewhere. Which suit does their outline suggest?', [['Hearts ♥',()=>choose('hearts')],['Spades ♠',()=>choose('spades')],['Clubs ♣',()=>choose('clubs')],['Diamonds ♦',()=>choose('diamonds')]],{position:[-5.5,4.6,-7.1],target:[-5.5,1.2,-8.7]});
}
