export const CHAPTERS = [
  { room: 'hall', number: 'I', title: 'Down the rabbit hole', subtitle: 'A door is only small if you are too tall.' },
  { room: 'garden', number: 'II', title: 'An afternoon out of time', subtitle: 'Four appointments. A rabbit who cannot stay.' },
  { room: 'court', number: 'III', title: 'Her Majesty’s peculiar justice', subtitle: 'Mind the roses. And your head.' },
  { room: 'tower', number: 'IV', title: 'The house of impossible things', subtitle: 'Some things make sense only from another side.' },
];
export const initialState = () => ({version:1, room:'hall', solved:[], inventory:[], notes:[], size:33, minutes:0, hints:0, started:false, completed:false, bridgeFaces:{}, paintedRoses:[], route:[], assembly:[], discovered:[], settings:{sound:true,sensitivity:1,quality:'high',controls:'auto'}});
export function solve(state,id,note) {
  if(state.solved.includes(id))return false;
  state.solved.push(id); if(note)state.notes.push({title:PUZZLES[id]?.title||id,text:note,room:state.room});return true;
}
export const has=(s,id)=>s.solved.includes(id);
export function collect(s,id){if(!s.inventory.includes(id))s.inventory.push(id)}
export function canVisit(s,room){return room==='hall'||room==='garden'&&has(s,'ceiling')||room==='court'&&has(s,'signs')||room==='tower'&&has(s,'decree')}
export function normalize(v){return String(v).toLowerCase().replace(/[^a-z0-9]/g,'')}
export function checkAnswer(id,value){const p=PUZZLES[id];return p?.answers?.some(a=>normalize(a)===normalize(value))||false}
export function restoreState(raw){
  try{const s=JSON.parse(raw); if(s.version!==1||!Array.isArray(s.solved)||!CHAPTERS.some(c=>c.room===s.room))return initialState();const clean={...initialState(),...s};clean.settings={...initialState().settings,...s.settings};for(const key of ['inventory','notes','route','assembly','discovered','paintedRoses'])if(!Array.isArray(clean[key]))clean[key]=[];if(!clean.bridgeFaces||typeof clean.bridgeFaces!=='object')clean.bridgeFaces={};clean.notes=clean.notes.map(n=>{const p=Object.values(PUZZLES).find(p=>p.title===n.title);return p?.note?{...n,text:p.note}:n.title==='guards_seen'?{...n,text:'You inspected both uniforms. The Queen will expect your own count of the differences.'}:n});return clean}catch{return initialState()}
}
export const ITEMS={key:{name:'Triangular key',icon:'key',description:'A tiny brass key with a triangular tooth. Compare it with the locks.'},fan:{name:'Silk fan',icon:'fan',description:'A blue silk fan. A little wind should clear a lot of pepper smoke.'},brush:{name:'Red paint & brush',icon:'brush',description:'Everything a nervous gardener needs.'},rose_token:{name:'Gardener’s effigy',icon:'pawn',description:'A little wooden gardener. There is half a numeral painted below its collar.'},guard_token:{name:'Knave’s effigy',icon:'pawn',description:'The guilty guard, reduced to a wooden likeness. His tunic carries part of a number.'},alice_token:{name:'Your effigy',icon:'pawn',description:'A miniature likeness of you, won on the croquet lawn.'},amber:{name:'Amber sightline',icon:'eye',description:'The amber side of the house reveals 78.'},ivory:{name:'Ivory sightline',icon:'eye',description:'The pale side of the house reveals 32.'}};
export const PUZZLES={
 story:{title:'The unfinished story',kind:'story',eyebrow:'A book left open',description:'The rabbit has scattered the beginning of your story. Fit the ten memories into a story. The highlighted words belong to the book’s lock.',answers:['2135'],note:'The story begins with two glances, one late rabbit, three o’clock, then a tunnel of five metres. 2135.',hints:['Begin on the riverbank. The rabbit appears before it checks its watch.','Order the events, then read only the highlighted number words.','The story’s number words read TWO, ONE, THREE, FIVE. Enter 2135.']},
 shadow:{title:'More than a letter',kind:'shadow',eyebrow:'A brass curiosity',description:'“I am turned about, and still only half of myself. Do not forget the shape that follows me.” Turn the letter. Read it together with its shadow.',answers:['33'],note:'A sideways M becomes 3. Its shadow adds a second 3. Together, 33.',requires:'story',hints:['Rotate the M a quarter turn.','The object reads 3. The shadow repeats it.','Enter 33.']},
 arithmetic:{title:'The wrong multiplication table',kind:'code',eyebrow:'Lessons from a grinning cat',description:'4 × 5 = 12\n4 × 6 = 13\n4 × 7 = 14\n\nContinue this particular pattern. 4 times what makes 20?',answers:['13','4x13'],note:'Each step adds one to the answer. The cat’s table reaches 20 at 4 × 13.',requires:'shadow',hints:['This is a sequence, not ordinary multiplication.','From 14 to 20 takes six steps. Add six to 7.','The missing number is 13.']},
 letter:{title:'A name missing its beginning',kind:'code',eyebrow:'The little door wall',description:'The plaque reads LICE. Stand back and look at the arrangement of doors. Which letter has wandered off the name?',answers:['a'],note:'The doors form an A. The recovered note says: eating makes you grow; drinking makes you shrink.',requires:'arithmetic',hints:['Look at the silhouette of all five doors together.','They have two sloping sides and a crossbar.','The missing letter is A.']},
 biscuit:{title:'Eat me',kind:'height',eyebrow:'A very particular appetite',description:'A bite makes you taller. Choose a higher mark on the brass scale. Which mark lines up with the key on the high table?',answers:['55'],note:'At height 55, the tabletop and its triangular key are within reach.',requires:'letter',hints:['The key rests above your current eye level. Compare its height with the brass marks.','Choose the highest mark on the scale.','Eat to reach 55, then collect the key from the tall table.']},
 bottle:{title:'Drink me',kind:'height',eyebrow:'A smaller point of view',description:'A sip makes you smaller. Choose a lower mark on the brass scale, then compare yourself with the triangular door.',answers:['11'],note:'At height 11, you fit through the triangular door.',requires:'letter',hints:['Unlock the triangular door with the matching key.','The passage fits the smallest height on the scale.','Drink to reach 11.']},
 feet:{title:'Where are your feet?',kind:'code',eyebrow:'An inconvenient stretch',description:'You have become terribly long. The dial by your head reads 12. The full measure is 89. How much of you is still missing?',answers:['77'],note:'89 minus 12 is 77. The little ceiling hatch is the way out.',requires:'bottle',hints:['Subtract the part you can see from the whole.','Your whole measure is 89. Your head accounts for 12.','Enter 77, then look up at the ceiling opening.']},
 caterpillar:{title:'Advice in the smoke',kind:'code',eyebrow:'The 3:10 appointment',description:'The caterpillar answers your question with a slow breath from his hookah. Something takes shape above the mushroom. What do you see?',answers:['88'],note:'The caterpillar told you to find a solitary spotted mushroom among the roots west of his grove. He also said to look for objects that have no twin.',hints:['Each pair of stacked rings makes a numeral.','The same numeral appears twice.','Enter 88.']},
 mushroom:{title:'A bite from either side',kind:'action',eyebrow:'The caterpillar’s mushroom',description:'This little violet mushroom stands alone among the roots. Its cap is covered with pale spots. A message curls around the stem: a little from each side will make you yourself again.',note:'The mushroom restored your size to 33. Its message reads: “The hours follow each other…”'},
 messenger:{title:'The messenger’s strange reply',kind:'code',eyebrow:'The 4:25 appointment',description:'“I won the right to carry this invitation.”\n“You won?”\n“Won, of course. Won, won, won!”\n\nThe invitation has a single empty seal. Listen for what belongs there.',answers:['1','one'],note:'Won sounds like one. The invitation says “…but only the numeral on the clock…”',hints:['Read “won” aloud.','The number is a homophone of won.','Enter 1.']},
 kitchen:{title:'Too much pepper',kind:'action',eyebrow:'The 5:40 appointment',description:'The kitchen is lost in a cloud of pepper. There must be something nearby that can move the air.',note:'The fan cleared the kitchen. The cook bakes the Queen’s tarts. Her clue reads “…where the minute hand points…”',requires:'caterpillar',hints:['The caterpillar mentioned objects that are one of a kind.','There is a blue fan on a pedestal near the garden entrance.','Collect the fan, then use it here.']},
 tea:{title:'An invitation to tea',kind:'code',eyebrow:'The 6:00 appointment',description:'“No room! No room! Unless you have come to take tea?” The Hatter nudges an empty cup toward you. Its seal will accept one letter. His hat still carries its curious price tag.',answers:['t'],note:'Tea sounds like T. The last line reads “…at each appointment, counts.”',hints:['The 10/6 on the hat is a distraction.','Say the drink’s name aloud.','Enter T.']},
 minutes:{title:'The rabbit’s lost minutes',kind:'minutes',eyebrow:'Four meetings, one sentence',description:'Four messages, collected at four appointments. Fit their sentence together. The rabbit’s watch has four empty wheels.',answers:['2580'],note:'At 3:10, 4:25, 5:40 and 6:00, the minute hands point to 2, 5, 8 and 0. The lock opens with 2580.',hints:['Use the long hand, not the short hand.','10 minutes points at 2. 25 points at 5. Continue.','Enter 2580.']},
 signs:{title:'Which way is out?',kind:'signs',eyebrow:'The Cheshire crossing',description:'“The signs never lie,” says the cat. “They simply disagree.” The colored letters above the table belong to a lock. Every small sign points somewhere.',answers:['5210'],note:'The green, brown, amber and pink trails draw 5, 2, 1 and 0. The Queen’s garden opens at 5210.',requires:'minutes',hints:['Each same-colored trail traces a single digit. Ignore the other colors while tracing.','Read green, brown, amber, then pink.','The four digits are 5210.']},
 maze_garden:{title:'The garden path',kind:'code',eyebrow:'A gate in the hedge',description:'The brass dial says you are 33. The garden gate changes your number by −4. What does the gate become?',answers:['29'],note:'33 − 4 = 29 opens the rose garden.',hints:['Apply the sign to your normal measure, 33.','Subtract four.','Enter 29.']},
 maze_court:{title:'The tribunal path',kind:'code',eyebrow:'A gate in the hedge',description:'You are 33. The tribunal gate multiplies your number by 3. Which number belongs at the gate?',answers:['99'],note:'33 × 3 = 99 opens the tribunal.',hints:['Apply the ×3 sign to 33.','Triple your ordinary measure.','Enter 99.']},
 maze_croquet:{title:'The croquet path',kind:'code',eyebrow:'A gate in the hedge',description:'You are 33. The croquet gate adds 16. Which number opens it?',answers:['49'],note:'33 + 16 = 49 opens the croquet lawn.',hints:['Apply the +16 sign to 33.','Add sixteen.','Enter 49.']},
 roses:{title:'The Queen’s roses',kind:'roses',eyebrow:'A gardener’s emergency',description:'The gardeners planted white roses. Her Majesty asked for red. Find their paintbrush and put things right before she notices.',note:'You painted the white roses red. A grateful gardener gave you a wooden effigy.',requires:'maze_garden',hints:['The brush and red paint are on a small table by the hedge.','Collect the paint, return here and paint all five white blooms.','Equip the brush, walk around the bed, and paint each of the five white blooms.']},
 trial:{title:'The case of the missing tart',kind:'trial',eyebrow:'Her Majesty will hear you now',description:'Inspect the stolen tart and the two uniforms before giving evidence. The Queen expects accurate answers, and she does not like repeating herself.',note:'The cook baked the tarts. The Knave of Hearts stole them. His disguise has seven differences. The second question was who stole the tarts.',requires:'maze_court',hints:['The pepper cook mentioned her tarts. The crumbs form a heart. Compare both guards.','Count hat band, blade, moustache, gloves, heart color, heart orientation, and jacket trim.','Answer: the cook; the Knave of Hearts; 7; “Who stole the tarts?”']},
 croquet:{title:'A very unwilling croquet ball',kind:'croquet',eyebrow:'Three rebounds to win',description:'The hedgehog will roll in a straight line until it hits a numbered cushion. Trace the only path through three rebounds to flag 1. Enter each cushion number, then the flag.',answers:['4761'],note:'The winning course rebounds from 4, then 7, then 6, and reaches flag 1. You won a wooden likeness of yourself.',requires:'maze_croquet',hints:['Follow the dotted launch line to the first cushion. The orange blocks rule out the other routes.','The first rebound is 4. The second is 7.','Follow 4 → 7 → 6 → flag 1. Enter 4761.']},
 effigies:{title:'Off with their heads',kind:'effigies',eyebrow:'Three wooden witnesses',description:'The Queen’s command becomes a useful instruction. The paint on the figures seems incomplete. Stack them, then obey the command on the table. What do the exposed marks become?',answers:['54'],note:'With the heads hidden, the three effigies align into the number 54.',hints:['You need the gardener’s gift, the trial reward and the croquet reward.','Stack you, knave, gardener. Hide the heads to join the paint marks.','The joined marks read 54.']},
 decree:{title:'The letters that escaped',kind:'alphabet',eyebrow:'The Queen’s last sentence',description:'“Hah! I condemn you, a silly, impudent child, to a life of vague whims, bad jests, quaint fancies, and exile!”\n\nThe decree contains almost every letter. Which three are absent? Inspect the alphabet seal below.',answers:['rkz','rzk','krz','kzr','zrk','zkr'],note:'The decree uses every letter except R, K and Z. Three missing letters lead to the kings’ building instructions.',requires:'effigies',hints:['Mark each letter that appears in the sentence. Ignore punctuation and spaces.','Only three alphabet letters will remain unmarked.','R, K and Z are missing.']},
 gardeners_match:{title:'The gardeners’ tool chest',kind:'match',eyebrow:'Three gardeners, three seals',description:'The tools belong to the gardeners. Match the three numbers on their tunics to the seals on the chest.',answers:['257','275','527','572','725','752'],note:'You matched the three gardeners to their spade seals and opened the tool chest.',requires:'maze_garden',hints:['Read the numbers on all three gardeners’ tunics.','Choose their three matching spade seals on the chest.','The gardeners are 2, 5 and 7.']},
 assembly:{title:'The kings’ impossible house',kind:'assembly',eyebrow:'Two kings, one impossible house',description:'Arrange the folded brass-and-jade architectural pieces using the two kings’ instructions. Build from the bottom upward, and from left to right.',note:'The house is assembled. Two rings on the floor mark the viewing positions.',hints:['Begin with black 6 and black 4. Turn the black bridge face down so its 8 meets the matching 8 below.','Then red 6, 4 and 2. Turn the red bridge face down, matching the 9s. Finish with red 5 and 7.','Place: ♠6, ♠4, black bridge, ♥6, ♥4, ♥2, red bridge, ♥5, ♥7.']},
 final_lock:{title:'The other side of the dream',kind:'code',eyebrow:'The last lock',description:'Read the house from both marked viewpoints. The cat’s eyes tell you which color comes first. Four digits will let the morning in.',answers:['7832'],note:'Amber gives 78. Ivory gives 32. The cat’s amber eye comes first. The way home is 7832.',requires:'assembly',hints:['Stand on each floor ring and face the house. Fragments align into two numbers per side.','The left eye is amber. Read that side before ivory.','Enter 7832.']},
};
export const STORY_FRAGMENTS=[
 'By the river, you glance at your sister’s book TWO times.',
 'A white rabbit interrupts the quiet afternoon.',
 'Nothing about a passing rabbit seems very strange…',
 '…until he cries, “ONE moment late! Oh, my ears!”',
 'He draws a little watch from his waistcoat.',
 'Its hands show THREE o’clock.',
 'You follow him through the brambles.',
 'He disappears into a hole beneath a tree.',
 'After FIVE metres, the tunnel drops straight down.',
 'You land beside a book. Your story is waiting inside.',
];
export const ASSEMBLY_ORDER=['♠ 6','♠ 4','Black bridge','♥ 6','♥ 4','♥ 2','Red bridge','♥ 5','♥ 7'];
export function objective(s){
 if(s.completed)return 'You found your way home.';
 const room=s.room;
 if(room==='hall'){
  for(const [id,msg] of [['story','Reassemble the story in the open book.'],['shadow','Examine the brass letter and its shadow.'],['arithmetic','Solve the grinning cat’s multiplication table.'],['letter','Find the missing letter by the little doors.'],['biscuit','Find a way to reach the high table.']])if(!has(s,id))return msg;
  if(!s.inventory.includes('key'))return 'Collect the key from the high table.';
  if(!has(s,'door_unlock'))return 'Match the key to a lock among the little doors.';
  if(!has(s,'bottle'))return 'Become small enough to enter the door.';
  if(!has(s,'feet'))return 'Enter the little door and find your missing measure.';
  return 'Look up. Sometimes the way out is above you.';
 }
 if(room==='garden'){
  if(!has(s,'caterpillar'))return 'Keep the rabbit’s 3:10 appointment.';
  if(!has(s,'mushroom'))return 'Find the solitary mushroom among the roots.';
  if(!['messenger','kitchen','tea'].every(id=>has(s,id)))return 'Keep the remaining appointments. Save their clues.';
  if(!has(s,'minutes'))return 'Find what the four clock hands are telling you.';
  if(!has(s,'signs'))return 'Follow the colors at the Cheshire crossing.';
  return 'Enter the gate to the Queen’s garden.';
 }
 if(room==='court'){
  if(!has(s,'roses'))return 'Open the garden path and help the gardeners.';
  if(!has(s,'trial'))return 'Gather evidence and answer the Queen’s questions.';
  if(!has(s,'croquet'))return 'Win the Queen’s croquet game.';
  if(!has(s,'effigies'))return 'Bring the three wooden effigies together.';
  if(!has(s,'decree'))return 'Discover which letters escaped the decree.';
  return 'Enter the house of impossible things.';
 }
 if(!has(s,'assembly'))return 'Build the house according to the kings’ instructions.';
 if(!s.inventory.includes('amber')||!s.inventory.includes('ivory'))return 'View the house from both rings on the floor.';
 return 'Read the cat’s eyes and open the last lock.';
}
